#include <stdio.h>
#include <stdlib.h>
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include "projetil.h"
#include "struct.h"
#include "personagem.h"
#include "cenario.h"
